
.PHONY: all
all:
	@$(MAKE) -C CommandExecutor all
	@$(MAKE) -C DocumentView all
	@$(MAKE) -C Hardware all
	@$(MAKE) -C Logger all
	@$(MAKE) -C Logic all
	#@$(MAKE) -C Model all
	@$(MAKE) -C Schedulers all
	#@$(MAKE) -C Utils all
	#@$(MAKE) -C Views/CommandLineView all

.PHONY: clean
clean:
	@$(MAKE) -C CommandExecutor clean
	@$(MAKE) -C DocumentView clean
	@$(MAKE) -C Hardware clean
	@$(MAKE) -C Logger clean
	@$(MAKE) -C Logic clean
	#@$(MAKE) -C Model clean
	@$(MAKE) -C Schedulers clean
	#@$(MAKE) -C Utils clean
	#@$(MAKE) -C Views/CommandLineView clean

