
all: 
	@$(MAKE) -C Command all
	@$(MAKE) -C Commons all
	#@$(MAKE) -C DocumentView all
	#@$(MAKE) -C Hardware all
	@$(MAKE) -C Logic all
	#@$(MAKE) -C Model all
	@$(MAKE) -C Utils all
	@$(MAKE) -C Views/CommandLineView all
	#@$(MAKE) -C Views/WebServerView all
	#@$(MAKE) -C WebServer all

clean:
	@$(MAKE) -C Command clean
	@$(MAKE) -C Commons clean
	#@$(MAKE) -C DocumentView clean
	#@$(MAKE) -C Hardware clean
	@$(MAKE) -C Logic clean
	#@$(MAKE) -C Model clean
	@$(MAKE) -C Utils clean
	@$(MAKE) -C Views/CommandLineView clean
	#@$(MAKE) -C Views/WebServerView clean
	#@$(MAKE) -C WebServer clean
