
.PHONY: all
all: DocumentView-all DTO-all Hardware-all Logger-all Logic-all Model-all ReaderWriter-all Schedulers-all TimerView-all Utils-all

.PHONY: clean
clean: DocumentView-clean DTO-clean Hardware-clean Logger-clean Logic-clean Model-clean ReaderWriter-clean Schedulers-clean TimerView-clean Utils-clean

.PHONY: DocumentView-all
DocumentView-all:
	@$(MAKE) -C DocumentView all

.PHONY: DocumentView-clean
DocumentView-clean:
	@$(MAKE) -C DocumentView clean

.PHONY: DTO-all
DTO-all:
	@$(MAKE) -C DTO all

.PHONY: DTO-clean
DTO-clean:
	@$(MAKE) -C DTO clean

.PHONY: Hardware-all
Hardware-all:
	@$(MAKE) -C Hardware all

.PHONY: Hardware-clean
Hardware-clean:
	@$(MAKE) -C Hardware clean

.PHONY: Logger-all
Logger-all:
	@$(MAKE) -C Logger all

.PHONY: Logger-clean
Logger-clean:
	@$(MAKE) -C Logger clean

.PHONY: Logic-all
Logic-all:
	@$(MAKE) -C Logic all

.PHONY: Logic-clean
Logic-clean:
	@$(MAKE) -C Logic clean

.PHONY: Model-all
Model-all:
	@$(MAKE) -C Model all

.PHONY: Model-clean
Model-clean:
	@$(MAKE) -C Model clean

.PHONY: ReaderWriter-all
ReaderWriter-all:
	@$(MAKE) -C ReaderWriter all

.PHONY: ReaderWriter-clean
ReaderWriter-clean:
	@$(MAKE) -C ReaderWriter clean

.PHONY: Schedulers-all
Schedulers-all:
	@$(MAKE) -C Schedulers all

.PHONY: Schedulers-clean
Schedulers-clean:
	@$(MAKE) -C Schedulers clean

.PHONY: TimerView-all
TimerView-all:
	@$(MAKE) -C Views/TimerView all

.PHONY: TimerView-clean
TimerView-clean:
	@$(MAKE) -C Views/TimerView clean

.PHONY: Utils-all
Utils-all:
	@$(MAKE) -C Utils all

.PHONY: Utils-clean
Utils-clean:
	@$(MAKE) -C Utils clean
