
.PHONY: all
all: CommandExecutor-all DocumentView-all Hardware-all Logger-all Logic-all Model-all Schedulers-all

.PHONY: clean
clean: CommandExecutor-clean DocumentView-clean Hardware-clean Logger-clean Logic-clean Model-clean Schedulers-clean

.PHONY: CommandExecutor-all
CommandExecutor-all:
	@$(MAKE) -C CommandExecutor all

.PHONY: CommandExecutor-clean
CommandExecutor-clean:
	@$(MAKE) -C CommandExecutor clean

.PHONY: DocumentView-all
DocumentView-all:
	@$(MAKE) -C DocumentView all

.PHONY: DocumentView-clean
DocumentView-clean:
	@$(MAKE) -C DocumentView clean

.PHONY: Hardware-all
Hardware-all:
	@$(MAKE) -C Hardware all

.PHONY: Hardware-clean
Hardware-clean:
	@$(MAKE) -C Hardware clean

.PHONY: Logger-all
Logger-all:
	@$(MAKE) -C Logger all

.PHONY: Logger-clean
Logger-clean:
	@$(MAKE) -C Logger clean

.PHONY: Logic-all
Logic-all:
	@$(MAKE) -C Logic all

.PHONY: Logic-clean
Logic-clean:
	@$(MAKE) -C Logic clean

.PHONY: Model-all
Model-all:
	@$(MAKE) -C Model all

.PHONY: Model-clean
Model-clean:
	@$(MAKE) -C Model clean

.PHONY: Schedulers-all
Schedulers-all:
	@$(MAKE) -C Schedulers all

.PHONY: Schedulers-clean
Schedulers-clean:
	@$(MAKE) -C Schedulers clean
