#!/bin/bash
#
#       /etc/rc.d/init.d/ns-slapd
# ns-slapd      This shell script takes care of starting and stopping
#               ns-slapd (the Fedora Directory Server)
#
# Author: Brian Jones 
# This e-mail address is being protected from spambots. You need JavaScript enabled to view it
 
#
# chkconfig: 2345 13 87
# description: ns-slapd is the Fedora Directory Service daemon. \
# FDS can serve as a repository for (and, subsequently, a source of) \
# data for most of the resources listed in /etc/nsswitch.conf, such as \
# passwd or group entries.

# Source function library.
#. /etc/init.d/functions

RUNNABLE=/cygdrive/c/Work/irrigation/Irrigation/bin/Irrigation.exe
PIDFILE=/var/run/irrigation.pid

#if [ -f /etc/sysconfig/ns-slapd ]; then
#       . /etc/sysconfig/ns-slapd
#fi


start() {
        echo -n "Starting Irrigation System: "
        if [ -f $PIDFILE ]; then
                PID=`cat $PIDFILE`
                echo Irrigation System is already running: $PID
                exit 2;
        else
                $RUNNABLE
                RETVAL=$?
                echo
                #[ $RETVAL -eq 0 ] && touch /var/lock/subsys/ns-slapd
                #return $RETVAL
				
				ps af | grep Irrigation | awk '{print $1}' > $PIDFILE
        fi

}

stop() {
        echo -n "Shutting down Irrigation System: "
        if [ -f $PIDFILE ]; then
				cat $PIDFILE | xargs kill
				rm -f $PIDFILE
        else
                echo Irrigation System is already stopped
                exit 2;
        fi
}

status() {
        if [ -f $PIDFILE ]; then
                echo Irrigation System is running
        else
                echo Irrigation System is not running
        fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
		status
    #    status ns-slapd
		;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage:  {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $?