#! /bin/sh
### BEGIN INIT INFO
# Provides:          Irrigation System
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Manage Irrigation System Service
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin
DESC="Irrigation System"
NAME=irrigation

IRRIGATIOND=irrigation
DAEMON=/usr/share/irrigation/irrigation
PIDFILE=/var/run/irrigation.pid
UID=pi
GID=pi

SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Define LSB log_* functions.
. /lib/lsb/init-functions


do_start()
{
	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   other if daemon could not be started or a failure occured
	#start-stop-daemon --start --quiet --make-pidfile --pidfile $PIDFILE --exec $DAEMON --chuid $UID:$GID --background
	# HACK the pi user has not rights to change the thread priority
	start-stop-daemon --start --quiet --make-pidfile --pidfile $PIDFILE --exec $DAEMON --background
}

do_stop()
{
	# Return
	#   0 if daemon has been stopped
	#   1 if daemon was already stopped
	#   other if daemon could not be stopped or a failure occurred
	start-stop-daemon --stop --quiet --remove-pidfile --pidfile $PIDFILE --exec $DAEMON --chuid $UID:$GID --retry=TERM/30/KILL/5
}

case "$1" in
  start)
	log_daemon_msg "Starting $DESC" "$IRRIGATIOND"
	do_start
	case "$?" in
		0) log_end_msg 0 ;;
		1) log_progress_msg "already started"
		   log_end_msg 0 ;;
		*) log_end_msg 1 ;;
	esac

	;;
  stop)
	log_daemon_msg "Stopping $DESC" "$IRRIGATIOND"
	do_stop
	case "$?" in
		0) log_end_msg 0 ;;
		1) log_progress_msg "already stopped"
		   log_end_msg 0 ;;
		*) log_end_msg 1 ;;
	esac

	;;
  restart)
	$0 stop
	$0 start
	;;
  status)
	status_of_proc -p $PIDFILE $DAEMON $IRRIGATIOND && exit 0 || exit $?
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|status}" >&2
	exit 3
	;;
esac

: